import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'si' | 'ta';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    home: 'Home',
    appointments: 'Appointments',
    labResults: 'Lab Results',
    prescriptions: 'Prescriptions',
    healthCard: 'Health Card',
    profile: 'Profile',
    settings: 'Settings',
    logout: 'Logout',
    login: 'Login',
    register: 'Register',
    welcome: 'Welcome back',
    dashboard: 'Dashboard',
    language: 'Language',
    bookAppointment: 'Book Appointment',
    viewAll: 'View All',
    upcomingAppointments: 'Upcoming Appointments',
    recentLabResults: 'Recent Lab Results',
    activePrescriptions: 'Active Prescriptions',
    healthSummary: 'Health Summary',
    yourHealthOurPriority: 'Your Health, Our Priority',
    getStarted: 'Get Started',
    heroDescription: 'Experience modern healthcare management with easy appointment booking, instant access to medical records, and personalized care.',
    easyAppointments: 'Easy Appointments',
    easyAppointmentsDesc: 'Book, reschedule, or cancel appointments with just a few clicks',
    labResultsTitle: 'Lab Results',
    labResultsDesc: 'Access and download your lab results anytime, anywhere',
    digitalHealthCard: 'Digital Health Card',
    digitalHealthCardDesc: 'Keep all your health records in one secure place',
    expertDoctors: 'Expert Doctors',
    expertDoctorsDesc: 'Connect with experienced healthcare professionals',
    happyPatients: 'Happy Patients',
    expertDoctorsLabel: 'Expert Doctors',
    appointmentsLabel: 'Appointments',
    support247: '24/7 Support',
    howItWorks: 'How It Works',
    step1Title: 'Register',
    step1Desc: 'Create your account in minutes with basic information',
    step2Title: 'Book Appointment',
    step2Desc: 'Choose your doctor and preferred time slot',
    step3Title: 'Get Care',
    step3Desc: 'Visit your doctor and access records online',
    whyChooseUs: 'Why Choose HealthCare+',
    feature1Title: 'Advanced Technology',
    feature1Desc: 'State-of-the-art digital health platform with cutting-edge security',
    feature2Title: 'Certified Professionals',
    feature2Desc: 'Board-certified doctors with years of experience',
    feature3Title: 'Instant Access',
    feature3Desc: 'Access your health records anytime, anywhere',
    feature4Title: 'Affordable Care',
    feature4Desc: 'Quality healthcare at competitive prices',
    quickLinks: 'Quick Links',
    aboutUs: 'About Us',
    services: 'Services',
    contact: 'Contact',
    faq: 'FAQ',
    contactInfo: 'Contact',
    footerText: 'Providing quality healthcare services and management solutions.',
  },
  si: {
    home: 'මුල් පිටුව',
    appointments: 'හමුවීම්',
    labResults: 'රසායනාගාර ප්‍රතිඵල',
    prescriptions: 'බෙහෙත් වට්ටෝරු',
    healthCard: 'සෞඛ්‍ය කාඩ්පත',
    profile: 'පැතිකඩ',
    settings: 'සැකසුම්',
    logout: 'ඉවත්වන්න',
    login: 'ප්‍රවේශය',
    register: 'ලියාපදිංචිය',
    welcome: 'නැවත පැමිණීම සාදරයෙන්',
    dashboard: 'උපකරණ පුවරුව',
    language: 'භාෂාව',
    bookAppointment: 'හමුවීමක් වෙන්කරවන්න',
    viewAll: 'සියල්ල බලන්න',
    upcomingAppointments: 'ඉදිරි හමුවීම්',
    recentLabResults: 'මෑත රසායනාගාර ප්‍රතිඵල',
    activePrescriptions: 'ක්‍රියාකාරී බෙහෙත් වට්ටෝරු',
    healthSummary: 'සෞඛ්‍ය සාරාංශය',
    yourHealthOurPriority: 'ඔබේ සෞඛ්‍යය, අපේ ප්‍රමුඛතාවය',
    getStarted: 'ආරම්භ කරන්න',
    heroDescription: 'පහසු හමුවීම් වෙන් කිරීම්, වෛද්‍ය වාර්තා වලට ක්ෂණික ප්‍රවේශය සහ පුද්ගලික සත්කාර සමඟ නවීන සෞඛ්‍ය සේවා කළමනාකරණය අත්විඳින්න.',
    easyAppointments: 'පහසු හමුවීම්',
    easyAppointmentsDesc: 'ක්ලික් කිහිපයකින් හමුවීම් වෙන්කරවන්න, නැවත සකස් කරන්න හෝ අවලංගු කරන්න',
    labResultsTitle: 'රසායනාගාර ප්‍රතිඵල',
    labResultsDesc: 'ඕනෑම වේලාවක, ඕනෑම තැනක ඔබේ රසායනාගාර ප්‍රතිඵල වෙත ප්‍රවේශ වී බාගත කරන්න',
    digitalHealthCard: 'ඩිජිටල් සෞඛ්‍ය කාඩ්පත',
    digitalHealthCardDesc: 'ඔබේ සියලුම සෞඛ්‍ය වාර්තා එක ආරක්ෂිත ස්ථානයක තබා ගන්න',
    expertDoctors: 'ප්‍රවීණ වෛද්‍යවරු',
    expertDoctorsDesc: 'පළපුරුදු සෞඛ්‍ය සේවා වෘත්තිකයන් සමඟ සම්බන්ධ වන්න',
    happyPatients: 'සතුටු රෝගීන්',
    expertDoctorsLabel: 'ප්‍රවීණ වෛද්‍යවරු',
    appointmentsLabel: 'හමුවීම්',
    support247: '24/7 සහාය',
    howItWorks: 'එය ක්‍රියා කරන්නේ කෙසේද',
    step1Title: 'ලියාපදිංචි වන්න',
    step1Desc: 'මූලික තොරතුරු සමඟ විනාඩි කිහිපයකින් ඔබේ ගිණුම සාදන්න',
    step2Title: 'හමුවීමක් වෙන්කරවන්න',
    step2Desc: 'ඔබේ වෛද්‍යවරයා සහ කැමති වේලාව තෝරන්න',
    step3Title: 'සත්කාර ලබා ගන්න',
    step3Desc: 'ඔබේ වෛද්‍යවරයා හමුවී අන්තර්ජාලය හරහා වාර්තා වෙත ප්‍රවේශ වන්න',
    whyChooseUs: 'HealthCare+ තෝරාගන්නේ ඇයි',
    feature1Title: 'උසස් තාක්ෂණය',
    feature1Desc: 'අති නවීන ආරක්ෂාව සහිත නවීන ඩිජිටල් සෞඛ්‍ය වේදිකාව',
    feature2Title: 'සහතික කළ වෘත්තිකයන්',
    feature2Desc: 'වසර ගණනාවක පළපුරුද්ද ඇති බෝඩ් සහතික වෛද්‍යවරු',
    feature3Title: 'ක්ෂණික ප්‍රවේශය',
    feature3Desc: 'ඕනෑම වේලාවක, ඕනෑම තැනක ඔබේ සෞඛ්‍ය වාර්තා වෙත ප්‍රවේශ වන්න',
    feature4Title: 'දැරිය හැකි සත්කාර',
    feature4Desc: 'තරඟකාරී මිලකට ගුණාත්මක සෞඛ්‍ය සේවා',
    quickLinks: 'ඉක්මන් සබැඳි',
    aboutUs: 'අප ගැන',
    services: 'සේවා',
    contact: 'සම්බන්ධ වන්න',
    faq: 'නිතර අසනු ලබන ප්‍රශ්න',
    contactInfo: 'සම්බන්ධ වන්න',
    footerText: 'ගුණාත්මක සෞඛ්‍ය සේවා සහ කළමනාකරණ විසඳුම් සපයයි.',
  },
  ta: {
    home: 'முகப்பு',
    appointments: 'சந்திப்புகள்',
    labResults: 'ஆய்வக முடிவுகள்',
    prescriptions: 'மருந்துச் சீட்டுகள்',
    healthCard: 'சுகாதார அட்டை',
    profile: 'சுயவிவரம்',
    settings: 'அமைப்புகள்',
    logout: 'வெளியேறு',
    login: 'உள்நுழைவு',
    register: 'பதிவு',
    welcome: 'மீண்டும் வரவேற்கிறோம்',
    dashboard: 'டாஷ்போர்டு',
    language: 'மொழி',
    bookAppointment: 'சந்திப்பு பதிவு',
    viewAll: 'அனைத்தையும் பார்க்க',
    upcomingAppointments: 'வரவிருக்கும் சந்திப்புகள்',
    recentLabResults: 'சமீபத்திய ஆய்வக முடிவுகள்',
    activePrescriptions: 'செயலில் உள்ள மருந்துச் சீட்டுகள்',
    healthSummary: 'சுகாதார சுருக்கம்',
    yourHealthOurPriority: 'உங்கள் சுகாதாரம், எங்கள் முன்னுரிமை',
    getStarted: 'தொடங்குங்கள்',
    heroDescription: 'எளிதான சந்திப்பு முன்பதிவு, மருத்துவ பதிவுகளுக்கான உடனடி அணுகல் மற்றும் தனிப்பயனாக்கப்பட்ட பராமரிப்புடன் நவீன சுகாதார மேலாண்மையை அனுபவிக்கவும்.',
    easyAppointments: 'எளிதான சந்திப்புகள்',
    easyAppointmentsDesc: 'சில கிளிக்குகளில் சந்திப்புகளை பதிவு செய்யுங்கள், மாற்றியமைக்கவும் அல்லது ரத்து செய்யவும்',
    labResultsTitle: 'ஆய்வக முடிவுகள்',
    labResultsDesc: 'எப்போது வேண்டுமானாலும், எங்கிருந்தும் உங்கள் ஆய்வக முடிவுகளை அணுகி பதிவிறக்கவும்',
    digitalHealthCard: 'டிஜிட்டல் சுகாதார அட்டை',
    digitalHealthCardDesc: 'உங்கள் அனைத்து சுகாதார பதிவுகளையும் ஒரே பாதுகாப்பான இடத்தில் வைத்திருங்கள்',
    expertDoctors: 'நிபுணர் மருத்துவர்கள்',
    expertDoctorsDesc: 'அனுபவம் வாய்ந்த சுகாதார நிபுணர்களுடன் தொடர்பு கொள்ளுங்கள்',
    happyPatients: 'மகிழ்ச்சியான நோயாளிகள்',
    expertDoctorsLabel: 'நிபுணர் மருத்துவர்கள்',
    appointmentsLabel: 'சந்திப்புகள்',
    support247: '24/7 ஆதரவு',
    howItWorks: 'இது எவ்வாறு செயல்படுகிறது',
    step1Title: 'பதிவு செய்யுங்கள்',
    step1Desc: 'அடிப்படை தகவலுடன் சில நிமிடங்களில் உங்கள் கணக்கை உருவாக்கவும்',
    step2Title: 'சந்திப்பு பதிவு செய்யுங்கள்',
    step2Desc: 'உங்கள் மருத்துவரையும் விருப்பமான நேரத்தையும் தேர்வு செய்யுங்கள்',
    step3Title: 'பராமரிப்பு பெறுங்கள்',
    step3Desc: 'உங்கள் மருத்துவரை சந்தித்து ஆன்லைனில் பதிவுகளை அணுகவும்',
    whyChooseUs: 'HealthCare+ ஏன் தேர்வு செய்ய வேண்டும்',
    feature1Title: 'மேம்பட்ட தொழில்நுட்பம்',
    feature1Desc: 'அதிநவீன பாதுகாப்புடன் கூடிய நவீன டிஜிட்டல் சுகாதார தளம்',
    feature2Title: 'சான்றிதழ் பெற்ற நிபுணர்கள்',
    feature2Desc: 'பல ஆண்டுகள் அனுபவம் கொண்ட வாரிய சான்றிதழ் பெற்ற மருத்துவர்கள்',
    feature3Title: 'உடனடி அணுகல்',
    feature3Desc: 'எப்போது வேண்டுமானாலும், எங்கிருந்தும் உங்கள் சுகாதார பதிவுகளை அணுகவும்',
    feature4Title: 'மலிவு பராமரிப்பு',
    feature4Desc: 'போட்டி விலையில் தரமான சுகாதார பராமரிப்பு',
    quickLinks: 'விரைவு இணைப்புகள்',
    aboutUs: 'எங்களைப் பற்றி',
    services: 'சேவைகள்',
    contact: 'தொடர்பு கொள்ளுங்கள்',
    faq: 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    contactInfo: 'தொடர்பு',
    footerText: 'தரமான சுகாதார சேவைகள் மற்றும் மேலாண்மை தீர்வுகளை வழங்குதல்.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
